import { defineNuxtModule } from "@nuxt/kit";
import { readdir, stat, writeFile } from "fs/promises";
import { basename, extname, join } from "path";

interface ModuleOptions {
	paths: string[];
}

export default defineNuxtModule<ModuleOptions>({
	defaults: {
		paths: ["app/components"],
	},
	meta: {
		compatibility: {
			nuxt: "^3.0.0 || ^4.0.0",
		},
		configKey: "wrikkaReexport",
		name: "@wrikka/reexport-module",
	},

	async setup(options, nuxt) {
		// Generate re-export files
		await generateReexports(options, nuxt);

		// Watch for changes in specified paths
		nuxt.hook("builder:watch", async (event, path) => {
			for (const basePath of options.paths) {
				if (path.includes(basePath)) {
					await generateReexports(options, nuxt);
					break;
				}
			}
		});
	},
});

async function generateReexports(options: ModuleOptions, nuxt: any) {
	// Generate index file for each path
	for (const basePath of options.paths) {
		const folderPath = join(nuxt.options.srcDir, basePath);
		await generateFolderIndex(folderPath, basePath);
	}
}

async function generateFolderIndex(
	folderPath: string,
	folderName: string,
) {
	try {
		// Check if folder exists
		try {
			await stat(folderPath);
		} catch {
			return;
		}

		// Read all files in the folder
		const files = await readdir(folderPath);

		// Filter for Vue files
		const vueFiles = files.filter((file) => extname(file) === ".vue");

		if (vueFiles.length === 0) {
			return;
		}

		// Generate export statements
		let content = `// Auto-generated index file for ${folderName} components\n`;
		content += `// This file is automatically generated by @wrikka/reexport-module\n\n`;

		for (const file of vueFiles) {
			const componentName = basename(file, ".vue");
			content += `export { default as ${componentName} } from './${componentName}.vue'\n`;
		}

		const indexPath = join(folderPath, "index.ts");
		await writeFile(indexPath, content, "utf-8");
	} catch (error) {
		// Silent fail
	}
}